version: '3.9'
services:
  bot:
    build:
      context: .
    depends_on:
      - db
    environment:
      INCIDENTS_DIGEST_CHANNEL: 'incidents'
      SLACK_SIGNING_SECRET: ''
      SLACK_BOT_TOKEN: ''
      SLACK_VERIFICATION_TOKEN: ''
      SLACK_WORKSPACE_ID: 'myslackworkspace'
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: foobar1234
      DATABASE_PORT: 5432
      INCIDENT_AUTO_GROUP_INVITE_ENABLED: 'false'
      INCIDENT_AUTO_GROUP_INVITE_GROUP_NAME: ''
      INCIDENT_EXTERNAL_PROVIDERS_ENABLED: 'false'
      INCIDENT_EXTERNAL_PROVIDERS_LIST: ''
      INCIDENT_AUTO_CREATE_FROM_REACT_ENABLED: 'false'
      INCIDENT_AUTO_CREATE_FROM_REACT_EMOJI_NAME: ''
      INCIDENT_GUIDE_LINK: ''
      INCIDENT_POSTMORTEMS_LINK: ''
      INCIDENT_CHANNEL_TOPIC: ''
      STATUSPAGE_INTEGRATION_ENABLED: 'false'
      STATUSPAGE_API_KEY: ''
      STATUSPAGE_PAGE_ID: ''
      STATUSPAGE_URL: ''
    expose:
      - 3000
    links:
      - db
  db:
    image: postgres:13
    hostname: db
    environment:
      POSTGRES_PASSWORD: 'foobar1234'
      POSTGRES_USER: 'postgres'
    expose:
      - 5432
  nginx:
    build: ./nginx
    depends_on:
      - bot
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
