apiVersion: v2
name: janus
version: 1.0.1
kubeVersion: '>= 1.19.0'
description: A Helm chart to deploy Janus, a ChatOps Slack bot for incident management.
type: application
keywords:
  - chatops
  - slack
  - incident-management
  - python
home: https://github.com/echoboomer/janus
sources:
  - https://github.com/echoboomer/janus
maintainers:
  - name: Scott Hawkins
    email: scott@echoboomer.net
    url: https://github.com/echoboomer
icon: https://github.com/echoboomer/janus/raw/main/assets/janus-icon.png
appVersion: '1.0.0'
