version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    versioning-strategy: auto
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    versioning-strategy: auto
    
