name: Run unit tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.9']
    env:
      # default: multiprocessing
      # threading is more stable on GitHub Actions
      BOLT_PYTHON_MOCK_SERVER_MODE: threading
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install "pytest>=7.1.2"
          pip3 install "pytest-dotenv>=0.5.2"
      - name: Run tests
        run: |
          pytest -vv tests/
